// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rarluubwuolndizlqkyq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJhcmx1dWJ3dW9sbmRpemxxa3lxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5MTM5NjUsImV4cCI6MjA3MzQ4OTk2NX0.I7JDKsB-yYYv7WaXZ6eyIjcF1rN6hxNE1G2GixSbbF4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});